AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation harjoitus 1

Parameters:
  MyBucketName:
    Description: My bucket name
    Type: String
    Default: joona-cloudformation-bucket

  MyInstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m2.large
    Description:
      Enter t2.micro, m1.small, or m2.large. Default is t2.micro.
  
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'


  
  
Resources:
  MyBucketResource:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref MyBucketName
  
  MySQSResource:
    Type: AWS::SQS::Queue

  MyInstanceResource:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref MyInstanceType
      ImageId: !Ref LatestAmiId

  JoonaLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        - subnet-01e1a1602b2d2c344
        - subnet-058b077402278a0d3
        - subnet-04f794da21a1b1293
      